{
 "title": "Device Authentication Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total auth attempts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_attempts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total active connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_connections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total successful authentications",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total failed authentications",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (auth_failures_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total auth attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "auth_attempts_total{job=\"analytics-worker-app\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "active_connections_total{job=\"analytics-worker-app\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Failing Devices Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (auth_failures_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}